<?php $this->layout('layout::default', ['title' => $title, 'activeNavLink' => 'home']) ?>
<div class="container">
  <div class="m-t-md">
    <h1>Expressive CRUD</h1>
  </div>
  <p class="lead">Simple CRUD application based on <a href="https://github.com/zendframework/zend-expressive">zend-expressive</a>.</p>
  <hr>
  <p class="lead">
    <a class="btn btn-primary-outline" href="/user-list" role="button">Users</a>
  </p>
</div>
