<?php $this->layout('layout::default', ['title' => $title, 'activeNavLink' => 'user-list']) ?>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-12">
      <h1 class="m-y-md">Users list</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>username</th>
            <th>email</th>
            <th>
              <a class="btn btn-success-outline btn-sm m-x pull-right"
                 href="/user-add" role="button">add</a>
            </th>
          </tr>
        </thead>
        <tbody>
          <?php $i = 1 ?>
          <?php foreach ($usersList as $user): ?>
          <tr>
            <th scope="row"><?= $i ?></th>
            <td><?= $this->e($user['username']) ?></td>
            <td><?= $this->e($user['email']) ?></td>
            <td>
                <a class="btn-delete btn btn-danger-outline btn-sm m-x pull-right"
                   href="#" userId="<?= $this->e($user['id']) ?>" role="button">delete</a>
                <a class="btn btn-warning-outline btn-sm m-x pull-right"
                   href="/user-edit/<?= $this->e($user['id']) ?>" role="button">edit</a>
            </td>
          </tr>
          <?php ++$i ?>
          <?php endforeach ?>
        </tbody>
      </table>
    </div>
  </div>
</div>
<?php $this->start('user-list-scripts') ?>
<script>
$(document).ready(function() {
  $(".btn-delete").on("click", function(event) {
    event.preventDefault();
    var userRow = $(this).closest("tr");
    $.ajax({
      url: "/user-delete",
      method: "post",
      data: {
        id: $(this).attr("userId")
      },
      success: function(data) {
        if (data.success) {
            userRow.remove();
            alert('User was deleted.');
        } else if (data.message) {
            alert('Error! ' + data.message);
        } else {
            alert('Unknown Error.');
        }
      }
    });
  });
});
</script>
<?php $this->stop('user-list-scripts') ?>
